-- Create the trigger function
CREATE OR REPLACE FUNCTION sb_55313.l16.fn_rcsa_alert_management_audit()
RETURNS TRIGGER AS $$
BEGIN
    IF (TG_OP = 'INSERT' OR TG_OP = 'UPDATE') THEN
        INSERT INTO sb_55313.l16.drm.rcsa_alert_management_audit (
            audit_id,
            alert_id,
            rule_id,
            rule_version,
            l1_risk_id,
            l2_risk_id,
            l3_risk_id,
            business_function_l1_id,
            business_function_l2_id,
            business_function_l3_id,
            business_function,
            country,
            legal_entity,
            stage,
            created_date,
            type_of_alert,
            alert_status,
            process_name,
            process_risk_rating,
            inherent_risk,
            latest_risk_rating,
            last_approved_final_risk_rating,
            assigned_role,
            updated_date,
            updated_by,
            last_action_taken,
            last_action_date,
            latest_reminder_date,
            escalation_date,
            action_case_id,
            country_id,
            legal_entity_id,
            inherent_risk_value,
            last_approved_final_risk_value,
            latest_risk_rating_value,
            created_by,
            l1_risk_name,
            l2_risk_name,
            l3_risk_name,
            business_function_l1_name,
            business_function_l2_name,
            business_function_l3_name,
            process_id
        )
        VALUES (
            nextval('sb_55313.l16.drm.rcsa_alert_management_audit_audit_id_seq'),
            NEW.alert_id,
            NEW.rule_id,
            NEW.rule_version,
            NEW.l1_risk_id,
            NEW.l2_risk_id,
            NEW.l3_risk_id,
            NEW.business_function_l1_id,
            NEW.business_function_l2_id,
            NEW.business_function_l3_id,
            NEW.business_function,
            NEW.country,
            NEW.legal_entity,
            NEW.stage,
            NEW.created_date,
            NEW.type_of_alert,
            NEW.alert_status,
            NEW.process_name,
            NEW.process_risk_rating,
            NEW.inherent_risk,
            NEW.latest_risk_rating,
            NEW.last_approved_final_risk_rating,
            NEW.assigned_role,
            NEW.updated_date,
            NEW.updated_by,
            NEW.last_action_taken,
            NEW.last_action_date,
            NEW.latest_reminder_date,
            NEW.escalation_date,
            NEW.action_case_id,
            NEW.country_id,
            NEW.legal_entity_id,
            NEW.inherent_risk_value,
            NEW.last_approved_final_risk_value,
            NEW.latest_risk_rating_value,
            NEW.created_by,
            NEW.l1_risk_name,
            NEW.l2_risk_name,
            NEW.l3_risk_name,
            NEW.business_function_l1_name,
            NEW.business_function_l2_name,
            NEW.business_function_l3_name,
            NEW.process_id
        );
        
    ELSIF (TG_OP = 'DELETE') THEN
        INSERT INTO sb_55313.l16.drm.rcsa_alert_management_audit (
            audit_id,
            alert_id,
            rule_id,
            rule_version,
            l1_risk_id,
            l2_risk_id,
            l3_risk_id,
            business_function_l1_id,
            business_function_l2_id,
            business_function_l3_id,
            business_function,
            country,
            legal_entity,
            stage,
            created_date,
            type_of_alert,
            alert_status,
            process_name,
            process_risk_rating,
            inherent_risk,
            latest_risk_rating,
            last_approved_final_risk_rating,
            assigned_role,
            updated_date,
            updated_by,
            last_action_taken,
            last_action_date,
            latest_reminder_date,
            escalation_date,
            action_case_id,
            country_id,
            legal_entity_id,
            inherent_risk_value,
            last_approved_final_risk_value,
            latest_risk_rating_value,
            created_by,
            l1_risk_name,
            l2_risk_name,
            l3_risk_name,
            business_function_l1_name,
            business_function_l2_name,
            business_function_l3_name,
            process_id
        )
        VALUES (
            nextval('sb_55313.l16.drm.rcsa_alert_management_audit_audit_id_seq'),
            OLD.alert_id,
            OLD.rule_id,
            OLD.rule_version,
            OLD.l1_risk_id,
            OLD.l2_risk_id,
            OLD.l3_risk_id,
            OLD.business_function_l1_id,
            OLD.business_function_l2_id,
            OLD.business_function_l3_id,
            OLD.business_function,
            OLD.country,
            OLD.legal_entity,
            OLD.stage,
            OLD.created_date,
            OLD.type_of_alert,
            OLD.alert_status,
            OLD.process_name,
            OLD.process_risk_rating,
            OLD.inherent_risk,
            OLD.latest_risk_rating,
            OLD.last_approved_final_risk_rating,
            OLD.assigned_role,
            OLD.updated_date,
            OLD.updated_by,
            OLD.last_action_taken,
            OLD.last_action_date,
            OLD.latest_reminder_date,
            OLD.escalation_date,
            OLD.action_case_id,
            OLD.country_id,
            OLD.legal_entity_id,
            OLD.inherent_risk_value,
            OLD.last_approved_final_risk_value,
            OLD.latest_risk_rating_value,
            OLD.created_by,
            OLD.l1_risk_name,
            OLD.l2_risk_name,
            OLD.l3_risk_name,
            OLD.business_function_l1_name,
            OLD.business_function_l2_name,
            OLD.business_function_l3_name,
            OLD.process_id
        );
    END IF;

    RETURN NULL;
END;
$$ LANGUAGE plpgsql;


-- Drop existing trigger if any
DROP TRIGGER IF EXISTS trg_rcsa_alert_management_audit ON sb_55313.l16.drm.rcsa_alert_management;

-- Create the trigger
CREATE TRIGGER trg_rcsa_alert_management_audit
AFTER INSERT OR UPDATE OR DELETE
ON sb_55313.l16.drm.rcsa_alert_management
FOR EACH ROW
EXECUTE FUNCTION sb_55313.l16.fn_rcsa_alert_management_audit();